import { P2PAd } from './types';

export const mockAds: P2PAd[] = [
    {
        id: '1',
        nickname: 'CryptoKing',
        avatar: 'CK',
        isMerchant: true,
        orders: 1245,
        completionRate: 98.5,
        responseTimeMin: 5,
        price: 1.02,
        available: 5420.5,
        minLimit: 100,
        maxLimit: 5000,
        payments: ['Bank Transfer', 'Zelle'],
        requiresVerification: false,
        type: 'buy',
        asset: 'USDT',
        fiat: 'USD'
    },
    {
        id: '2',
        nickname: 'FastTrader',
        avatar: 'FT',
        isMerchant: true,
        orders: 850,
        completionRate: 99.1,
        responseTimeMin: 2,
        price: 1.01,
        available: 1200,
        minLimit: 50,
        maxLimit: 1200,
        payments: ['Wise', 'Revolut'],
        requiresVerification: false,
        type: 'buy',
        asset: 'USDT',
        fiat: 'USD'
    },
    {
        id: '3',
        nickname: 'SecureEx',
        avatar: 'SE',
        isMerchant: false,
        orders: 120,
        completionRate: 95.0,
        responseTimeMin: 15,
        price: 1.03,
        available: 25000,
        minLimit: 1000,
        maxLimit: 25000,
        payments: ['Bank Transfer'],
        requiresVerification: true,
        type: 'buy',
        asset: 'USDT',
        fiat: 'USD'
    },
    {
        id: '4',
        nickname: 'GlobalBit',
        avatar: 'GB',
        isMerchant: true,
        orders: 3400,
        completionRate: 99.8,
        responseTimeMin: 1,
        price: 0.99,
        available: 15000,
        minLimit: 500,
        maxLimit: 10000,
        payments: ['Cash in Person', 'Bank Transfer'],
        requiresVerification: false,
        type: 'sell',
        asset: 'USDT',
        fiat: 'USD'
    }
];